// Copyright 2026, Greg Bussell, All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "QuestNodeBase.generated.h"

class UQuestReward;

UCLASS(Abstract, Blueprintable)
class SIMPLEQUEST_API UQuestNodeBase : public UObject
{
    GENERATED_BODY()

    friend class FQuestlineGraphCompiler;

public:
    DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnNodeActivated, UQuestNodeBase*, Node, FGameplayTag, InContextualTag);
    DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnNodeCompleted, UQuestNodeBase*, Node, bool, bDidSucceed);

    FOnNodeActivated OnNodeActivated;
    FOnNodeCompleted OnNodeCompleted;

    /**
     * Activate this node with the given contextual tag. Sets ContextualTag and fires OnNodeActivated. Override in subclasses
     * to add activation behavior.
     */
    virtual void Activate(FGameplayTag InContextualTag);
    
    /** Resolve a raw, editor-time FName tag created by the graph compiler into the registered runtime FGameplayTag */
    void ResolveQuestTag(FName TagName);

protected:
    /**
     * Stable save key. Derived from the authoring node's GUID at compile time. Never hand-edited. Forms part of the GUID
     * chain for save data keying in linked graphs.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FGuid QuestContentGuid;

    /**
     * Standalone routing tag for this node. Generated by the compiler from the questline asset name and node label. Used
     * for all event bus routing.
     * 
     * Format: Quest.<QuestlineName>.<SanitizedNodeLabel>
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    FGameplayTag QuestTag;

    /**
     * Call-site routing tag assigned by the subsystem at activation time. Equals QuestTag for root-level and standalone
     * nodes. Differs for nodes inside a shared linked graph where the parent provides a unique prefix.
     */
    UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly)
    FGameplayTag ContextualTag;

    /** Tags of nodes to activate on successful completion. Compiler-written. */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesOnSuccess;

    /** Tags of nodes to activate on failed completion. Compiler-written. */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TSet<FName> NextNodesOnFailure;

    /**
     * Prerequisite tags that must be satisfied before this node can be started. Compiler-written from connected Prereq
     * Reference nodes in the graph.
     *
     * Format: QuestPrereq.*
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    TArray<FName> PrereqTags;

    /** Reward granted on completion of this node. */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
    TSoftClassPtr<UQuestReward> Reward;

    /**
     * Whether completing this node should also complete the parent graph. Replaces bCompletesQuestline; works at any
     * graph depth.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    bool bCompletesParentGraph = false;

    /**
     * Whether activation of this node waits for a registered quest giver rather than starting immediately. Compiler-written
     * based on the presence of a giver-gate in the graph.
     */
    UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
    bool bGiverGated = false;

public:
    FORCEINLINE FGuid GetQuestGuid() const { return QuestContentGuid; }
    FORCEINLINE FGameplayTag GetQuestTag() const { return QuestTag; }
    FORCEINLINE FGameplayTag GetContextualTag() const { return ContextualTag; }
    FORCEINLINE void SetContextualTag(const FGameplayTag InTag) { ContextualTag = InTag; }
    FORCEINLINE const TSet<FName>& GetNextNodesOnSuccess() const { return NextNodesOnSuccess; }
    FORCEINLINE const TSet<FName>& GetNextNodesOnFailure() const { return NextNodesOnFailure; }
    FORCEINLINE bool DoesCompleteParentGraph() const { return bCompletesParentGraph; }
    FORCEINLINE bool IsGiverGated() const { return bGiverGated; }
    
};
